enroll/urls.py
from django.urls import path
from .views import sign_up, user_login, profile, user_logout,password_with_old, password_with_reset, dashboard
urlpatterns = [
    path('signup/', sign_up,name='signup'),
    path('login/',user_login,name='login'),
    path('profile/',profile,name='profile'),
    path('logout/',user_logout, name='logout'),
    path('password/',password_with_old, name='password'),
    path('passwordreset/',password_with_reset, name='passwordreset'),
    path('dashboard/',dashboard,name='dashboard'),
]

user_create/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('enroll.urls')),
]

enroll/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=300) 

enroll/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}   

from django.contrib.auth.forms import UserChangeForm
class EditUserForm(UserChangeForm):
    password=None
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email', 'date_joined']
        labels = {'email':'Email'}

enroll/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from sqlalchemy import true
# from django.contrib.auth.forms import UserCreationForm
from . forms import SignUpForm, EditUserForm
# Create your views here.
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm , SetPasswordForm
from django.contrib.auth import authenticate, login, logout , update_session_auth_hash
from django.contrib.auth.models import Group
def sign_up(request):
    if request.method == 'POST':
        fm = SignUpForm(request.POST)
        if fm.is_valid():
            user = fm.save()
            group = Group.objects.get(name='Editor')
            user.groups.add(group)
            messages.success(request,"Account created successfully...")
        fm=SignUpForm()
    else:
        fm=SignUpForm()
    return render(request,'enroll/signup.html',{"form":fm})


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            fm = AuthenticationForm(request,data=request.POST)
            if fm.is_valid():
                username = fm.cleaned_data['username']
                password = fm.cleaned_data['password']
                user = authenticate(username=username,password=password)
                if user is not None:
                    login(request,user)
                    messages.success(request,"logged in successfully...")
                    return HttpResponseRedirect('/users/profile/')
        else:
            fm = AuthenticationForm()
        return render(request,'enroll/login.html',{"form":fm})
    else:
        return HttpResponseRedirect('/users/profile/')


def profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = EditUserForm(request.POST,instance=request.user )
            if fm.is_valid():
                fm.save()
                messages.success(request,"edit successfully")
        else:
            fm = EditUserForm(instance = request.user)
        return render(request,'enroll/profile.html',{'name':request.user, 'form':fm})
    else:
        return HttpResponseRedirect('/users/login/')

from django.contrib.auth.models import Group
def dashboard(request):
    if request.user.is_authenticated:
        return render(request,'enroll/dashboard.html',{'user':request.user})
    else:
        return HttpResponseRedirect('/users/login/')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/users/login/')

def password_with_old(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = PasswordChangeForm(user=request.user,data=request.POST)
            if fm.is_valid():
                fm.save()
                update_session_auth_hash(request,fm.user)
                return HttpResponseRedirect('/users/profile/')
        else:
            fm = PasswordChangeForm(user=request.user)
    else:
        return HttpResponseRedirect('/users/login/')
    return render(request,'enroll/passwordold.html',{'form':fm})

def password_with_reset(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            fm = SetPasswordForm(user=request.user,data=request.POST)
            if fm.is_valid():
                fm.save()
                update_session_auth_hash(request,fm.user)
                return HttpResponseRedirect('/users/profile/')
        else:
            fm = SetPasswordForm(user=request.user)
    else:
        return HttpResponseRedirect('/users/login/')
    return render(request,'enroll/passwordreset.html',{'form':fm})

enroll/templates/enroll/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Hello...{{user.username}}</h2>
    {% if perms.enroll.delete_blog %}
    <input type="button" value="Delete">
    {% else %}
    <p>No delete permission</p>
    {% endif %}
    {% if perms.enroll.add_blog %}
    <input type="button" value="add">
    {% else %}
    <p>No add permission</p>
    {% endif %}
    {% if perms.enroll.change_blog %}
    <input type="button" value="change">
    {% else %}
    <p>No change permission</p>
    {% endif %}
    <a href="{% url 'logout' %}">logout</a>
</body>
</html>

enroll/templates/enroll/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                {{error}}
            {% endfor %}
        {% endif %}
        {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
        {% endfor %}
        <input type="submit" value="submit">
    </form>
    <a href="{% url 'signup' %}">signup</a>
</body>
</html>

enroll/templates/enroll/passwordold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> <br>
        {% endfor %}
        <input type="submit" value="submit">    
    </form>
    <a href="{% url 'profile' %}">profile</a>
    
</body>
</html>

enroll/templates/enroll/passwordreset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> <br>
        {% endfor %}
        <input type="submit" value="submit">    
    </form>
    <a href="{% url 'profile' %}">profile</a>
</body>
</html>

enroll/templates/enroll/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Hello {{name}}</h2>
    {% if messages %}
    {% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% endif %}
        {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> <br>   
        {% endfor %}
        <input type="submit" value="submit">
    </form>
    <a href="{% url 'logout' %}">logout</a>
    <a href="{% url 'password' %}">Change with old password</a>
    <a href="{% url 'passwordreset' %}">Change with reset password</a>
</body>
</html>

enroll/templates/enroll/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                {{error}}
            {% endfor %}
        {% endif %}
        {% for fm in form %}
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
    {% if messages %}
    {% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</small>
    {% endfor %}
    {% endif %}
    <a href="{% url 'login' %}">login</a>
</body>
</html>